include xcmix/conversion/deg2rad.sco
include xcmix/conversion/dx2x.sco
include xcmix/conversion/f2m.sco
include xcmix/conversion/f2mel.sco
include xcmix/conversion/l2str.sco
include xcmix/conversion/loc2amp.sco
include xcmix/conversion/mel2f.sco
include xcmix/conversion/pol2car.sco
include xcmix/conversion/r2c.sco
include xcmix/conversion/r2dur.sco
include xcmix/conversion/r2m.sco
include xcmix/conversion/rad2deg.sco
include xcmix/conversion/x2dx.sco