include xcmix/random/_irand.sco
include xcmix/random/_rand.sco
include xcmix/random/_randlist.sco
include xcmix/random/_random.sco
include xcmix/random/_trand.sco
include xcmix/random/irandlist.sco
include xcmix/random/randchoice.sco
include xcmix/random/randlist.sco
include xcmix/random/randomlist.sco
include xcmix/random/shuffle.sco
include xcmix/random/trandlist.sco
include xcmix/random/wrandchoice.sco